### ISSUE TITLE
Question of Background

### ISSUE THREAD

**Issue by yinxiangshi** [willfaught/paige#1]
Hi!

Thanks for your good template. I really like your design.

Currently, I am trying to modify this theme, I want to change the background with vanta.js(https://github.com/tengbao/vanta). However, I don't know where should I start. Could you please give me any guide?

You can see my web in `allonsyj.com`

Thanks for your help!

**Comment by willfaught** [comment]
Thanks :)

It depends on how you want to use it. If you want it to apply to every page, then I would add it to the bottom of the head or body tags, which you could do either in yourwebsite/layouts/partials/{head.html,body.html} (see {head,body}.html mentioned in the readme) or paige/layouts/_default/{baseof,home,list,single,taxonomy}.html. Doing it in head.html or body.html would mean you wouldn't have to fork paige. You just have to paste the vanta script tags in one of those files.

Does that cover your needs?

**Comment by yinxiangshi** [comment]
> Thanks :)
> 
> It depends on how you want to use it. If you want it to apply to every page, then I would add it to the bottom of the head or body tags, which you could do either in yourwebsite/layouts/partials/{head.html,body.html} (see {head,body}.html mentioned in the readme) or paige/layouts/_default/{baseof,home,list,single,taxonomy}.html. Doing it in head.html or body.html would mean you wouldn't have to fork paige. You just have to paste the vanta script tags in one of those files.
> 
> Does that cover your needs?

Really thanks for your explanation! Where can I buy u a coffee? Again, thanks for your beautiful theme!

**Comment by willfaught** [comment]
You're welcome. :)

I only have Square Cash ($willfaught) and Venmo (@willfaught). Donations are much appreciated, but not expected. :)

**Comment by yinxiangshi** [comment]
plz leave ur email so that I can send u a gift card.

**Comment by willfaught** [comment]
If you send it to github@willfaught.com, I'll receive it.

**Comment by yinxiangshi** [comment]
Thank u! Plz remember to check your email

Will Faught ***@***.***> 于2022年11月16日周三 13:41写道：

**Comment by willfaught** [comment]
I received the card. Thank you so much! :)

**Comment by yinxiangshi** [comment]
Hope u can keep going! I support u!
