### ISSUE TITLE
Unable to build site

### ISSUE THREAD

**Issue by justinryanc** [willfaught/paige#10]
Unable to build site due to error below... any idea what I'm doing wrong?

Start building sites …
hugo v0.111.1-39a4a3cf676533859217805c36181c7a3dfa321c+extended windows/amd64 BuildDate=2023-03-02T10:08:26Z VendorInfo=gohugoio
ERROR 2023/03/08 16:36:18 render of "taxonomy" failed: "C:\Users\jrcha\OneDrive\Documents\hugo\justinryanc\themes\paige\layouts\_default\baseof.html:33:11": execute of template failed: template: _default/taxonomy.html:33:11: executing "_default/taxonomy.html" at <partial "paige/scripts.html" $page>: error calling partial: "C:\Users\jrcha\OneDrive\Documents\hugo\justinryanc\themes\paige\layouts\partials\paige\scripts.html:47:3": execute of template failed: template: partials/paige/scripts.html:47:3: executing "partials/paige/scripts.html" at <partial "paige/script.html" (dict "src" "paige/bootstrap/bootstrap.bundle.js")>: error calling partial: "C:\Users\jrcha\OneDrive\Documents\hugo\justinryanc\themes\paige\layouts\partials\paige\script.html:20:26": execute of template failed: template: partials/paige/script.html:20:26: executing "partials/paige/script.html" at <$href>: undefined variable: $href
ERROR 2023/03/08 16:36:18 render of "taxonomy" failed: "C:\Users\jrcha\OneDrive\Documents\hugo\justinryanc\themes\paige\layouts\_default\baseof.html:33:11": execute of template failed: template: _default/taxonomy.html:33:11: executing "_default/taxonomy.html" at <partial "paige/scripts.html" $page>: error calling partial: "C:\Users\jrcha\OneDrive\Documents\hugo\justinryanc\themes\paige\layouts\partials\paige\scripts.html:47:3": execute of template failed: template: partials/paige/scripts.html:47:3: executing "partials/paige/scripts.html" at <partial "paige/script.html" (dict "src" "paige/bootstrap/bootstrap.bundle.js")>: error calling partial: "C:\Users\jrcha\OneDrive\Documents\hugo\justinryanc\themes\paige\layouts\partials\paige\script.html:20:26": execute of template failed: template: partials/paige/script.html:20:26: executing "partials/paige/script.html" at <$href>: undefined variable: $href
Error: Error building site: failed to render pages: render of "home" failed: "C:\Users\jrcha\OneDrive\Documents\hugo\justinryanc\themes\paige\layouts\_default\baseof.html:33:11": execute of template failed: template: _default/list.html:33:11: executing "_default/list.html" at <partial "paige/scripts.html" $page>: error calling partial: "C:\Users\jrcha\OneDrive\Documents\hugo\justinryanc\themes\paige\layouts\partials\paige\scripts.html:47:3": execute of template failed: template: partials/paige/scripts.html:47:3: executing "partials/paige/scripts.html" at <partial "paige/script.html" (dict "src" "paige/bootstrap/bootstrap.bundle.js")>: error calling partial: "C:\Users\jrcha\OneDrive\Documents\hugo\justinryanc\themes\paige\layouts\partials\paige\script.html:20:26": execute of template failed: template: partials/paige/script.html:20:26: executing "partials/paige/script.html" at <$href>: undefined variable: $href
Built in 16 ms

**Comment by willfaught** [comment]
Which version are you using?

**Comment by justinryanc** [comment]
> Which version are you using?

45.0

**Comment by BaiqingL** [comment]
Having the same problem

**Comment by willfaught** [comment]
Sorry about that. That looks like a copy/paste error. I published a fix in v0.46.0. Please try it out.

**Comment by jotwg** [comment]
Tried v0.46.1:

```
Start building sites … 
hugo v0.111.2-4164f8fef9d71f50ef3962897e319ab6219a1dad+extended linux/amd64 BuildDate=2023-03-05T12:32:20Z VendorInfo=gohugoio
Error: Error building site: TOCSS-DART: failed to transform "paige/bootstrap/paige.scss" (text/x-scss): "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/willfaught/paige@v0.46.1/assets/paige/bootstrap/paige.scss:4:8": Can't find stylesheet to import.

```

**Comment by jotwg** [comment]
ok, after adding the mounts in config.yaml it seems to work now so far.

thx

**Comment by justinryanc** [comment]
> ok, after adding the mounts in config.yaml it seems to work now so far. (instructions should be updated accordingly)
> 
> thx

Would you explain what mount you did?  I am getting same error you got.

**Comment by jotwg** [comment]
see the 'module:' lines in config.yaml under project's root dir (https://github.com/willfaught/paige/blob/master/config.yaml)

**Comment by justinryanc** [comment]
> see the 'module:' lines in config.yaml under the root dir of this repo (https://github.com/willfaught/paige/blob/master/config.yaml), i.e. add them to your config.yaml

That did it, thanks!  I had tried adding them but didn't include the module: line just the mount: line.  Appreciate the help!

**Comment by willfaught** [comment]
I updated the install instructions to make the mount config clearer. Sorry for the confusion.

The original issue seems resolved, so closing this.
