### ISSUE TITLE
shortcodes/paige/image.html: param "style" is missing

### ISSUE THREAD

**Issue by jotwg** [willfaught/paige#14]
Can't pass parameter "style" to paige/img shortcode, I think image.html should look like this:
```
{{ $alt := .Get "alt" }}
{{ $link := .Get "link" }}
{{ $height := .Get "height" }}
{{ $maxheight := .Get "maxheight" }}
{{ $maxwidth := .Get "maxwidth" }}
{{ $method := .Get "method" }}
{{ $options := .Get "options" }}
{{ $style := .Get "style" }}
{{ $src := .Get 0 | default (.Get "src") }}
{{ $title := .Get "title" }}
{{ $width := .Get "width" }}

{{ if not $src }}
    {{ errorf "paige/image: no content" }}
{{ end }}

{{ $content := partial "paige/img.html" (dict
    "alt" $alt
    "class" "img-fluid"
    "height" $height
    "maxheight" $maxheight
    "maxwidth" $maxwidth
    "method" $method
    "options" $options
    "style" $style
    "page" .Page
    "src" $src
    "title" $title
    "width" $width
) }}

{{ if $link }}
    {{ $content = partial "paige/a.html" (dict
        "content" $content
        "href" $link
    ) }}
{{ end }}

<div class="paige-image">{{ $content }}</div>

```

cheers

**Comment by willfaught** [comment]
Hi @jotwg, thanks for the suggestion. I’d like to understand your situation. What would you set style for?

**Comment by jotwg** [comment]
see my reply email

**Comment by willfaught** [comment]
What email? I only see these two messages:

> Can't pass parameter "style" to paige/img shortcode [...]

> see my reply email

**Comment by jotwg** [comment]
-------- Forwarded Message --------
Subject: Re: [willfaught/paige] shortcodes/paige/image.html: param 
"style" is missing (Issue #14)
Date: Sat, 25 Mar 2023 20:47:53 +0100
From: Joeri Canis ***@***.***>
To: Will Faught ***@***.***>

Hi,

On 25.03.2023 20:10, Will Faught wrote:
> Hi @jotwg <https://github.com/jotwg>, thanks for the suggestion. I’d 
> like to understand your situation. What would you set style for?for example "float: left;" etc. for small images, see 
https://cloudi.myfirewall.org/camino2007/vorbereitungen/
(sorry, site is in German only and still in draft...)

I've to admit that I switched to hugo-profile because it's design fits a 
bit better to my ideas.
However, your code looks *way* better (as far as I can judge, I'm a 
total Hugo newbie), so I'm about to "steal" some pieces here and there, 
that's why I'm looking at  your shortcodes...

**Comment by willfaught** [comment]
>However, your code looks *way* better (as far as I can judge, I'm a
total Hugo newbie), so I'm about to "steal" some pieces here and there,
that's why I'm looking at  your shortcodes...

Thanks!

>https://cloudi.myfirewall.org/camino2007/vorbereitungen/

What is it you need to style here? Which CSS properties would you set?

**Comment by jotwg** [comment]
in this case:

```
style="margin: 0px 5px 5px 0px; float: left; border:0;"
```
i.e. I want to let images float to the left or right (or even to the center, but that's more difficult) and define reasonable margins.

**Comment by willfaught** [comment]
There's a paige/figure shortcode that can wrap a paige/image that provides floating, centering, and margins. For example, see https://willfaught.com/paige/shortcodes/figure/#float-parameter and https://willfaught.com/paige/shortcodes/image/#figure. Is that sufficient?

**Comment by jotwg** [comment]
indeed!

(should read the docs more thoroughly, sorry...)
