### ISSUE TITLE
Any plan to support photoswipe?

### ISSUE THREAD

**Issue by mobilelifeful** [willfaught/paige#19]
Thank you for sharing this theme with a lot features. Wonder if you plan to support 
https://github.com/dimsemenov/photoswipe ?
Thank you.

**Comment by willfaught** [comment]
Which feature(s) specifically do you need? A lightbox? A masonry layout?

**Comment by mobilelifeful** [comment]
> Thank you for sharing this theme with a lot features. Wonder if you plan to support https://github.com/dimsemenov/photoswipe ? Thank you.

Not sure if this features is lightbox or A masonry layout

from https://www.liwen.id.au/heg/

would like to able able to demonstrate like the blog above with picture, when visitors click on them to show a bigger one.

**Comment by willfaught** [comment]
The gallery shortcode currently links to the full images. If you click an image, the full size will be shown. Is that sufficient for your needs?

**Comment by mobilelifeful** [comment]
> The gallery shortcode currently links to the full images. If you click an image, the full size will be shown. Is that sufficient for your needs?

Thank you for the quick response.  test out again from
https://willfaught.com/paige/shortcodes/gallery/
When people click on the image of 
https://willfaught.com/paige/shortcodes/gallery/1-2.jpg
it does show full size of it, which leads average non-tech "lost", and it doesn't seem to bring a "hd" version of the same image.

**Comment by willfaught** [comment]
I want to make sure I understand. Also, I think I might have not been clear enough.

If you go to the "Images parameter" section at https://willfaught.com/paige/shortcodes/gallery/#images-parameter, then click the three images in that section, the browser will navigate to the image alone, where it can be shown at the full size.

Are you saying that non-technical people would be lost doing that? If so, I don't understand why, since users can use the back button to navigate back to the gallery.

Can you explain what you mean by HD version? Do you mean displaying the full size of the image, as much as possible?

**Comment by mobilelifeful** [comment]
> I want to make sure I understand. Also, I think I might have not been clear enough.
> 
> If you go to the "Images parameter" section at https://willfaught.com/paige/shortcodes/gallery/#images-parameter, then click the three images in that section, the browser will navigate to the image alone, where it can be shown at the full size.
> 
> Are you saying that non-technical people would be lost doing that? If so, I don't understand why, since users can use the back button to navigate back to the gallery.
> 
> Can you explain what you mean by HD version? Do you mean displaying the full size of the image, as much as possible?

Yes, I believe _non-technical_ people would be "lost",   
first, they may never understand/think that the image can be click on, which lost some data/point of sharing the image. second, once they are in the new tab with the full size of image without any nav for them, some of they will close current tab. 

It's a UX thing, when mouse over an image or finger over an image, an enlarge icon / hand sign will guide them to see the full size picture, then in the full size picture mode, a return arrow or a close sign will guide them back to continue the reading. 
<img width="58" alt="Screen Shot 2023-04-05 at 1 56 08 AM" src="https://user-images.githubusercontent.com/91811647/230032627-eae08fd7-5553-4596-8c29-b7db43884b82.png">


<img width="1484" alt="image" src="https://user-images.githubusercontent.com/91811647/230031894-7ffdb9b4-970b-489f-ad58-4aff50eaf897.png">


HD, trying to mean high Resolution Images

**Comment by willfaught** [comment]
>first, they may never understand/think that the image can be click on, which lost some data/point of sharing the image. 

Earlier, you wrote: "mouse over the image, it show that the image can be view in HD, like a + icon." It seems that this approach would have the same problem: the user has to hover over the image. Currently, if you hover over the gallery images, your mouse's pointer will change to a hand, indicating it's clickable (although only if you use the `images` parameter). If the user knows how browsers work, then wouldn't they understand what this means, and how to navigate backward after finishing with the image?

>second, once they are in the new tab with the full size of image without any nav for them, some of they will close current tab.

By default, it navigates to the image in the same tab. But they also have the option to open the link in a new tab. If they use the same tab, they will have the browser's toolbar, so they can click the back button. I don't see how this might be confusing. It would only be confusing if navigation with browsers in general is confusing, it seems to me.

**Comment by willfaught** [comment]
There hasn't been a response, so closing.
