### ISSUE TITLE
mailto link preprends base URL

### ISSUE THREAD

**Issue by admannz** [willfaught/paige#2]
With the Social email config in config.yaml, the mailto link

I.e. this is the resulting link  from this in config.yaml

      email:
        icon: envelope
        link: mailto:user@email.com
        name: E-mail

is

https://basesite.com/user@email.com

**Comment by willfaught** [comment]
@admannz Sorry for the delay responding. Somehow I was unsubscribed from issue notifications.

It looks like you're using an older version. The relevant code has changed quite a bit. Do you still see the issue?

**Comment by willfaught** [comment]
Closing this issue for now. If you have more to add, please reopen the issue.
