### ISSUE TITLE
Missing menus

### ISSUE THREAD

**Issue by jwp23** [willfaught/paige#21]
I am trying to install the theme and do not see the menu. I copied the `exampleSite` as outlined in #16 .

When I run in the root directory of my repo the command
`hugo server --source ./ --themesDir ./themes`
I don't see the menu. I also tried
`hugo server -D` 
 and I get the same result

When I use the `exampleSite` directory in the theme, with the below command I see the menu
`hugo server --source ./themes/paige/exampleSite --themesDir ../..`

**Comment by willfaught** [comment]
This is how Paige does it:

https://github.com/willfaught/paige/blob/master/.github/workflows/pages.yml#L28-L29

Run hugo server in exampleSite, and tell it the path to the directory that contains Paige with --themesDir. For example:

```sh
$ git checkout ...
$ cd paige/exampleSite
$ hugo server --themesDir ../..
```

**Comment by jwp23** [comment]
Thanks for the prompt response. I can see that the site builds with the menus when I cd into `./themes/paige/exampleSite` and run the `hugo server --themesDir ../..`. What I'm not clear on is why the menus are not showing when I copy the contents of the `./themes/paige/exampleSite` into my root directory and run the `hugo server -D`` command.

**Comment by jwp23** [comment]
I think I know what happened. I had both a `config.toml` and a `config.yaml` in my root directory. I converted the contents of the `config.yaml` to toml and added them to `config.toml`. I removed the `config.yaml`. Now I see the menus.

**Comment by willfaught** [comment]
OK, I’m glad it’s resolved.

Note that the recommended way to install Paige is to import it as a module. See the readme instructions for that.

**Comment by jwp23** [comment]
Yes, I imported Paige as a module. The instructions were a bit confusing. I followed the Hugo Quickstart guide and then followed your installation instructions in the README.

**Comment by willfaught** [comment]
What was confusing about the Paige instructions?

**Comment by jwp23** [comment]
It wasn't clear whether I needed to follow the Hugo Quickstart to install the theme.

**Comment by willfaught** [comment]
Thanks, that's helpful. How did the config.yaml examples conflict?

**Comment by jwp23** [comment]
I thought the `config.yaml` was something theme specific as opposed to `config.toml` which I thought was Hgo specific. I had both files in my root directory. It wasn't until I combined the two that my issue was resolved.

**Comment by willfaught** [comment]
@jwp23 What do you think of [the new setup section in the readme](https://github.com/willfaught/paige/commit/66c2ea9d6d84947bb25b0455620e180b0fd0263d)? You can see it live at https://github.com/willfaught/paige. Does that avoid the confusion?

**Comment by jwp23** [comment]
@willfaught That is clearer. One question I have is it necessary to use git submodules instructions int the hugo get started guide if you import the Paige module with the `hugo mod` command and adding the module to the `config.toml`? One other note is that it would be clearer if you explained whether you only need the `config.toml` that comes with the `hugo new site` command or whether you can have both `config.toml` that comes with the `hugo new site` and the `config.yaml` file that you use in the examples.

**Comment by willfaught** [comment]
Importing as a module with hugo mod is separate from putting a copy of Paige into your themes directory with git submodule. The themes directory is the old way of doing things. Perhaps it’s confusing to include the Hugo getting started link at all.

I use YAML for my own stuff, so I was thinking if you know Hugo, you’ll know that config.yaml and config.toml are equivalent. I guess that’s not clear if you don’t know Hugo well, and want to get started with Paige quickly. I suppose it would be clearer for the docs to use TOML too. I dislike TOML, but I perhaps it’s worth ignoring that here. :)

**Comment by jwp23** [comment]
I'll have to try using the theme without using the git submodule. I think it's ok to use yaml for the documentation as long as it's clear that it's one or the other. I used a yaml to toml online converter to take your configuration samples and put it into my `config.toml`. I like yaml but I want to learn toml.

**Comment by willfaught** [comment]
I converted the YAML to TOML in the readme: https://github.com/willfaught/paige/commit/f5994891eda3da6bcc83b765839ccc140c5dce33

**Comment by willfaught** [comment]
I also added links to Hugo's install and module guides.

**Comment by willfaught** [comment]
I'm going to close this, since I've made all the changes I planned. If you still see an issue, please reopen this or open a new issue.
