### ISSUE TITLE
Working with vanilla install of dart-sass-embedded on Linux 

### ISSUE THREAD

**Issue by provsoumya** [willfaught/paige#22]
I have an issue where we're deploying to a hosted platform on Azure (Azure Static Websites) which supports Hugo. However, the build system doesn't allow custom install of linux packages for me to rely on. To workaround this, I am installing and `untaring` the relevant dart embedded tarball as a pre-build step. It should work after this where I have the executable added to the environment path. But it isn't. So my question is, isn't just unzipping the tarball and adding it to the environment path, enough?

Pre-build step output for the install: 
```
/opt/sass_embedded:
total 8
-rwxr-xr-x 1 root root  614 Mar 23 23:25 dart-sass-embedded
drwxr-xr-x 2 root root 4096 Apr  5 20:41 src

/opt/sass_embedded/src:
total 8804
-rw-r--r-- 1 root root   76090 Mar 23 23:25 LICENSE
-rwxr-xr-x 1 root root 5153880 Mar 23 23:25 dart
-rw-r--r-- 1 root root 3777328 Mar 23 23:25 dart-sass-embedded.snapshot
```
and the path is : 
```
PATH=/opt/sass_embedded:/opt/hugo/0.111.3:/usr/local/go/bin:/opt/python/latest/bin:/opt/oryx:/opt/yarn/stable/bin:/opt/hugo/lts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

And here's the Hugo build failure: 
```
error calling partial: "/github/workspace/themes/paige/layouts/partials/paige/link.html:30:35": execute of template failed: template: partials/paige/link.html:30:35: executing "partials/paige/link.html" at <toCSS (dict "enableSourceMap" $enablesourcemap "includePaths" $includepaths "outputStyle" $outputstyle "transpiler" "dartsass")>: error calling toCSS: exec: "dart-sass-embedded": executable file not found in $PATH
```

**Comment by willfaught** [comment]
The paths look correct. I’m unfamiliar with the Azure environment. What does “which dart-sass-embedded“ output? What about “hugo env”? What happens if you try to do the same setup locally?

**Comment by provsoumya** [comment]
This is the underlying hosting platform: https://learn.microsoft.com/en-us/azure/static-web-apps/publish-hugo 

The Hugo env looks right as well: 
```
Hugo environment:
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.20.1"
github.com/sass/libsass="3.6.5"
github.com/webmproject/libwebp="v1.2.4"
github.com/sass/dart-sass-embedded/protocol="1.2.0"
github.com/sass/dart-sass-embedded/compiler="1.60.0"
github.com/sass/dart-sass-embedded/implementation="1.60.0"
```
And the output for `which dart-sass-embedded`:
```
/opt/sass_embedded/dart-sass-embedded
```

**Comment by willfaught** [comment]
That looks right. What happens when you run it locally? And what is the Hugo command being used?

**Comment by willfaught** [comment]
Does this fix your issue? https://discourse.gohugo.io/t/installing-dart-sass-embedded/32468/10

**Comment by willfaught** [comment]
Also: https://discourse.gohugo.io/t/dart-sass-embedded-path-quandary/33639/6

**Comment by willfaught** [comment]
No response, so closing.

**Comment by willfaught** [comment]
No response, so closing.

**Comment by provsoumya** [comment]
Thanks for closing. I haven't figured out a solve yet. The critique I have for this sort of a platform dependency is some sort of provided build time hook that can manage the compilation of these artifacts. It seems disjointed to me. Thanks for the great support.
