### ISSUE TITLE
Cannot compile site

### ISSUE THREAD

**Issue by maxchristman** [willfaught/paige#27]
When I try to run `hugo server -D`, I get the following error:

`Error: add site dependencies: load resources: loading templates: "/tmp/hugo_cache/modules/filecache/modules/pkg/mod/github.com/willfaught/paige@v0.62.1/layouts/partials/paige/image.html:42:1": parse failed: template: partials/paige/image.html:42: function "continue" not defined`

The site fails to compile. Here is my Hugo environment if it's helpful:

`hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.18.1"`

**Comment by willfaught** [comment]
Paige requires at least Hugo v0.111.3 extended. Please see https://github.com/willfaught/paige#setup.

**Comment by maxchristman** [comment]
My bad, thank you for pointing that out.
