### ISSUE TITLE
Taxonomy pages (tags, categories, series) not outputting labeled content

### ISSUE THREAD

**Issue by ryvaeus** [willfaught/paige#33]
Hi! I'm having an issue with taxonomies not showing up in their collection pages, similar to [this issue](https://discourse.gohugo.io/t/taxonomy-page-not-displaying/20132).

My taxonomies in `hugo.toml` are
```
[taxonomies]
series = 'gamemagazine, gamebrosph, inquirer, unboxguru'
category = 'thoughts, crosspost, work'
tag = 'article, gaming, gadget, list, quotes, review, social'
```
And the front matter on a page I'm testing it out contains
```
---
title: 10 Videogames That Changed My Life
date: 2013-12-17T02:51:01.266Z
description: null
categories:
  - thoughts
tags:
  - gaming
  - list
series:
  - gamebrosph
---
```
The file tree looks like
```
.
└─ content
   ├─ blog
   │      └─ _index.md
   │      └─ 10-videogames-that-changed-my-life.md
   ├─ categories
   │  ├─ crosspost
   │  │  └─ _index.md
   │  ├─ thoughts
   │  │  └─ _index.md
   │  ├─ work
   │  │  └─ _index.md
   ├─ series
   │  ├─ gamebrosph
   │  │  └─ _index.md
   │  ├─ gamemagazine
   │  │  └─ _index.md
   │  ├─ inquirer
   │  │  └─ _index.md
   │  ├─ unboxguru
   │  │  └─ _index.md
   │  └─ _index.md
   ├─ tags
   │  ├─ article
   │  │  └─ _index.md
   │  ├─ gadget
   │  │  └─ _index.md
   │  ├─ gaming
   │  │  └─ _index.md
   │  ├─ list
   │  │  └─ _index.md
   │  ├─ quotes
   │  │  └─ _index.md
   │  ├─ review
   │  │  └─ _index.md
   │  ├─ social
   │  │  └─ _index.md
   │  └─ _index.md
   ├─ _index.md
   └─ search.md
```
... among other directories/files of course. Each `_index.md` only contains a description and title front matter, and the ones in `categories` and `tags` also have `layout: "paige/cloud"`.

I get no errors building the site, and see no noteworthy output in the debug logs when running `hugo server --disableFastRender --log-level debug`. The output of `hugo env` on my local machine is
```
hugo v0.115.2-8966424e0e521fb1627216a84efd2c5d5917cb0d+extended windows/amd64 BuildDate=2023-07-08T17:06:56Z VendorInfo=gohugoio
GOOS="windows"
GOARCH="amd64"
GOVERSION="go1.20.1"
github.com/sass/libsass="3.6.5"
github.com/webmproject/libwebp="v1.2.4"
github.com/sass/dart-sass-embedded/protocol="1.2.0"
github.com/sass/dart-sass-embedded/compiler="1.62.1"
github.com/sass/dart-sass-embedded/implementation="1.62.1"
```
I'll see about putting my site up on github shortly for easier examination. Appreciate any insight. Thanks!

Edit: I've created a [github project](https://github.com/ryvaeus/website) and deployed it with [Cloudflare Pages](https://website-akt.pages.dev/).

**Comment by willfaught** [comment]
I think you want

```toml
[taxonomies]
category = 'categories'
series = 'series'
tag = 'tags'
```

**Comment by willfaught** [comment]
Check out exampleSite/hugo.yaml to see how it works for the example site.

**Comment by ryvaeus** [comment]
I clearly still don't understand how Hugo works. Thank you!
