### ISSUE TITLE
Function "continue" not defined

### ISSUE THREAD

**Issue by FailedMesh** [willfaught/paige#37]
An error comes up after running "hugo server"

Error: add site dependencies: load resources: loading templates: "/home/failedmesh/hugo-demo/themes/paige/layouts/partials/paige/image.html:42:1": parse failed: template: partials/paige/image.html:42: function "continue" not defined

**Comment by willfaught** [comment]
I suspect you're using an old version of Hugo. The Paige readme setup section says you must use at least Hugo version 0.111.3.
