### ISSUE TITLE
Home link is active when on other pages when using language subdirs.

### ISSUE THREAD

**Issue by RossComputerGuy** [willfaught/paige#38]
Noticed on this page: https://expidusos.com/en/download/
![image](https://github.com/willfaught/paige/assets/19699320/efbc96ff-d6b1-4a55-877c-23c8575d8c48)

Download link should be active but not home.

Config: https://github.com/ExpidusOS/website/blob/3cc2948dad696c80cadd2a3c6f6b987b58f734a0/config/_default/languages.en.toml

**Comment by willfaught** [comment]
Thanks for reporting this, and thanks for the repro. This should be fixed in v0.65.4. Can you confirm?

**Comment by RossComputerGuy** [comment]
Yes, this fixes it. Thank you.
