### ISSUE TITLE
Dart-Sass instead of embedded Dart Sass

### ISSUE THREAD

**Issue by Keisn1** [willfaught/paige#39]
Hi @willfaught, 
I would really like to use the theme but I'm having trouble installing embedded Dart Sass with
brew install sass/sass/dart-sass-embedded@1.62.1

In the documentation of Hugo however, they say that you should just use Dart Sass.

"If you have been using Embedded Dart Sass[1] ([https://gohugo.io/hugo-pipes/transpile-sass-to-css/#fn:1]) with Hugo v0.113.0 and earlier, uninstall Embedded Dart Sass, then install Dart Sass. If you have installed both, Hugo will use Dart Sass."

Is there anything that comes to mind that speaks against that?

**Comment by willfaught** [comment]
Hi @Keisn1, thanks for reporting this. I've changed the setup instructions to use Dart Sass in v0.65.5. It looks like the Hugo transition to Dart Sass is complete. Please use `brew install sass/sass/sass` from now on.
