### ISSUE TITLE
Feature Request: Configuration To Open External Links in New Tab

### ISSUE THREAD

**Issue by saurabh-mish** [willfaught/paige#45]
Requesting feature for a configuration which opens external links in a new tab (from discussion #44).

**Comment by willfaught** [comment]
So this would happen for any link anywhere on any page, including the menu, the article body, or the footer?

I'd like to better understand the need for this. Can you describe why/when this would be used?

**Comment by saurabh-mish** [comment]
> So this would happen for any link anywhere on any page, including the menu, the article body, or the footer?

Yes

> I'd like to better understand the need for this. Can you describe why/when this would be used?

Let's say somebody adds an external profile like GitHub, StackOverflow, etc. When a visitor clicks the link which takes them there, they see a lot of things. 

For instance on GitHub, there are pinned project, contributions, personal README, etc. And on StackOverflow there is frequently asked questions, answered questions, profile information, most recent votes, saved posts, etc. Some visitors may dive into that content **and** may not remember to come back to the personal blog, or how many clicks its going to take for them to get back to where they were on the personal blog.

External links like these have a lot of content to "hook" the visitor onto. Opening external links in a new tab is to ensure that the visitor has a way of getting back to the personal blog because there's less distraction, ads, etc. and it's more about the person.

**Comment by willfaught** [comment]
>External links like these have a lot of content to "hook" the visitor onto

It sounds like the need is only for "big" links like you described, is that right? Or is there a need to do this for any link, like a link to a definition on dictionary.com or a post on someone's personal blog?

**Comment by saurabh-mish** [comment]
I think it's going to be easier to have a configuration flag which opens all external links in a new tab. 

"Big" links are going to vary and tough to keep track of. IMO all external links are "big".

**Comment by willfaught** [comment]
This is implemented in v0.67.0. Just published. See the new paige.external_link_new_tab site parameter.

Can you confirm it works for you?

**Comment by saurabh-mish** [comment]
It doesn't work - I updated the theme and see

```
module patterns.se

go 1.21.0

require github.com/willfaught/paige v0.68.0 // indirect
```

in the `go.mod` file and added 

```
[paige]
color = "#0d6efd" # Bootstrap primary color and theme color for Safari and Windows
external_link_new_tab = true # Open external links in new tabs
math = false # Enable math typesetting
```

at the bottom of the config file.

**Comment by willfaught** [comment]
What is your base url and external link?

**Comment by willfaught** [comment]
Also, what is the link syntax? Markdown or html?

**Comment by saurabh-mish** [comment]
> What is your base url and external link?

It's a website on a different domain. Navigation is from patterns.se to saurabh.sm and creativecommons.org and is happening in the footer. [This](https://codeberg.org/mishra/patterns.se) is the repository URL.

> Also, what is the link syntax? Markdown or html?

Markdown in `hugo.toml`

**Comment by willfaught** [comment]
I've been delayed looking into this because I picked up a new feature right before the problem was reported. Will work on this afterward.

**Comment by saurabh-mish** [comment]
Sure, thanks Will !

**Comment by willfaught** [comment]
external_link_new_tab belongs under params.paige, but you have just paige. You want this:

```toml
[params.paige]
external_link_new_tab = true
```

**Comment by willfaught** [comment]
@saurabh-mish Can you confirm that fixes the issue?

**Comment by saurabh-mish** [comment]
Hi @willfaught 

Yes it works !!

> external_link_new_tab belongs under params.paige, but you have just paige. 

Thanks a lot for pointing this out !!

**Comment by willfaught** [comment]
>Looks like this is not present is the README. Currently it looks like [this](https://github.com/willfaught/paige/blob/a8e900e26161fd8a0e3115e4519b3cb4f60345d6/README.md?plain=1#L182)

That documents the configuration object shared by the site and pages:

>There is a single parameter object with sensible defaults that can be overridden in site or page parameters:

In page front matter, it appears like this:

```go
+++
[paige]
external_link_new_tab = true
+++
```

In site configuration, it appears like this:

```go
[params.paige]
external_link_new_tab = true
```

**Comment by willfaught** [comment]
@saurabh-mish I added a line to the readme that should clarify this: https://github.com/willfaught/paige/commit/e4c6b388363f4aea3ab0d92a2b257a658640b280. Thanks for the feedback.
