### ISSUE TITLE
Feature Request: List Pages by Weight

### ISSUE THREAD

**Issue by saurabh-sm** [willfaught/paige#50]
The pages located [here](https://github.com/willfaught/paige/tree/master/exampleSite/content/content) have a weight associated with them.

But in [this listing](https://willfaught.com/paige/content/) on the example site, they appear to be listed by most recently updated.

Listing pages by weight would provide a way to order topics of a section, by difficulty for example.

**Comment by willfaught** [comment]
Good catch! Perhaps the group-by functionality drops the weight ordering. I'll have to look into this.

**Comment by willfaught** [comment]
https://discourse.gohugo.io/t/page-order-isnt-the-default-with-groupbypublishdate-and-page-weights/46635

**Comment by willfaught** [comment]
This should be fixed in v0.71.2. @saurabh-mish Can you confirm?

**Comment by saurabh-mish** [comment]
Yes, it works!

**Comment by saurabh-sm** [comment]
This doesn't seem to be working at the moment.
