### ISSUE TITLE
Strange licensing

### ISSUE THREAD

**Issue by svetogam** [willfaught/paige#53]
Your LICENSE file is the Apache 2.0 license, but you're using it in a strange way.

Because my website is [open source](https://codeberg.org/superpractica/website) and I modified some of your original files, I have to follow the "Redistribution" part of the Apache 2.0 license, which is section 4.

In simplified terms, section 4 gives these 4 requirements to me:

1. Keep a copy of the Apache 2.0 license.
2. Give notices in files I modified that I modified the files.
3. Retain copyright, etc. notices in the files I modified.
4. Retain a text file named "NOTICE".

Notice that there's no requirement of even giving attribution here. The requirement is rather to retain the notices that exist. You can look at how the [Apache Software Foundation](https://github.com/apache) does it for an example of how the license is intended to be used. They have a NOTICE file for the copyright notice (such as "Copyright 2017-2023 The Apache Software Foundation") and comments at the start of every code file giving license information.

You have no such notices, so I comply with the license requirements by adding this header to the files I modified:

    

But FYI it would still fulfill the license requirements if I only added this header:

    
    
Just to be clear, there's no legal problem with the way you're currently doing things, and I have no problem complying with these requirements. But it would help me and potentially other open source projects modifying your theme if you either document that you intend to use the license this way and it's not an oversight, or you license this in a less strange way. Either of these will give assurance that my requirements for complying with the license aren't likely to change in the future.

I can try to help with this, but please note that I'm not a lawyer and haven't talked with one. I just read the license closely.

**Comment by willfaught** [comment]
My apologies for the late response. I never saw an email notification.

Thank you for pointing this out. After review, I agree that the license requires copyright notices per file. I prefer the more modern method of applying the license per project with a single LICENSE file, so I changed the project's license to MIT. The copyright notice is in the LICENSE file, so you just need to reproduce that and associate it with the copied code. Hope that's agreeable with you!

**Comment by svetogam** [comment]
That works for me. Thanks!
