### ISSUE TITLE
Custom favicon

### ISSUE THREAD

**Issue by Matteo-Valerio** [willfaught/paige#54]
Is it possible to set a custom favicon?

Thank you

**Comment by apodl1** [comment]
Yes, I did that by adding a favicon.png (or .svg, not sure which one worked in the end) to the static/ -folder. It took a few reloads / rebuilds to get it to show through, probably because of browser cache or something like that.

**Comment by willfaught** [comment]
You must override the favicon files in your site. See the icon-related files in https://github.com/willfaught/paige/tree/master/static.

**Comment by Matteo-Valerio** [comment]
I followed your advice now everything works correctly. Thank you

> You must override the favicon files in your site. See the icon-related files in https://github.com/willfaught/paige/tree/master/static.
