### ISSUE TITLE
Disable dark mode

### ISSUE THREAD

**Issue by 0x0f0f0f** [willfaught/paige#56]
Is there a way of enabling only light/dark mode?

**Comment by willfaught** [comment]
There was a long time ago, but I dropped it because it seemed like most people would want the matching mode. What's your use case for doing that?

**Comment by 0x0f0f0f** [comment]
> There was a long time ago, but I dropped it because it seemed like most people would want the matching mode. What's your use case for doing that?

I'm making my friend's personal website and we would like to enforce  light mode only.

**Comment by willfaught** [comment]
I meant what is the reason for having only light mode? I'd like to better understand your motivation. Wouldn't it look better at night in dark mode?

**Comment by willfaught** [comment]
Closing since there's no response. Please reopen if you have more to add.

**Comment by willfaught** [comment]
I added a `paige.color_scheme` config option in the latest version. This should address your need.

**Comment by 0x0f0f0f** [comment]
Is it `v0.75.0`? I've set 
```
[paige]
color_scheme = "light"
```

In `hugo.toml` but it stays in dark mode.

**Comment by willfaught** [comment]
Yes, 75. I verified it works with the exampleSite in Safari and Chrome. Does that work for you? Be sure you don't have any browser extensions running that can affect the colors, like a dark mode extension.
