### ISSUE TITLE
shortcodes won't work since update

### ISSUE THREAD

**Issue by raumkauz** [willfaught/paige#57]
Hello, I hope you are well.

I built my website last year and just wanted to update something. I was surprised to find that shortcodes (or at least the shortcode paige/image) don't seem to work anymore. I also tested with the example site provided in the paige repo.

This is the Error when I build it with the hugo command:
"...\Homepage_Builder\content\_index.en.md:18:4": failed to extract shortcode: template for shortcode "paige/image" not found

Please help.

**Comment by willfaught** [comment]
I don't see an error when running the example site:

```
$ cd exampleSite
$ hugo server --enableGitInfo
Watching for changes in /Users/will/Developer/paige/{archetypes,assets,exampleSite,i18n,layouts,paige,static}
Watching for config changes in /Users/will/Developer/paige/exampleSite/hugo.toml, /Users/will/Developer/paige/hugo.toml, /Users/will/Developer/paige/exampleSite/go.mod
Start building sites … 
hugo v0.123.6-92684f9a26838a46d1a81e3c250fef5207bcb735+extended darwin/arm64 BuildDate=2024-02-28T18:29:40Z VendorInfo=brew


                   | EN   
-------------------+------
  Pages            | 170  
  Paginator pages  |   0  
  Non-page files   |  40  
  Static files     |  95  
  Processed images |  36  
  Aliases          |  42  
  Cleaned          |   0  

Built in 743 ms
Environment: "development"
Serving pages from disk
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1) 
Press Ctrl+C to stop
```

What are your versions of Hugo, Sass, and Paige? Does this error reproduce with the latest versions of each?

**Comment by raumkauz** [comment]
Hello, thank you for your quick response.

I got hugo v0.114.0-9df2ec7988e5a217a14901cc76c0b7e76b2e9f02+extended windows/amd64, which worked fine last time I used it. Never versions didn't work with the template for me. Maybe I should retry?

Sass is 1.69.5

Paige Version: paige v0.71.2 

Go Version: go 1.21.3

I didn't change anything yet hugo told me about issues with multilanguage and issues with shortcodes.

**Comment by willfaught** [comment]
Those versions seem fine, but try the latest version of each, just in case:

- Go: 1.22.0
- Hugo: v0.123.7+extended
- Sass: 1.71.1
- Paige: v0.71.4

What are the contents of your go.mod and hugo.toml?

What is the code you're using that references paige/image?

What is the Hugo output when you try to build the example site?

**Comment by raumkauz** [comment]
Hugo build output:

D:\Repos\Homepage_Builder>hugo
Start building sites …
hugo v0.114.0-9df2ec7988e5a217a14901cc76c0b7e76b2e9f02+extended windows/amd64 BuildDate=2023-06-19T17:01:43Z VendorInfo=gohugoio

Total in 1059 ms
Error: error building site: assemble: "D:\Repos\Homepage_Builder\content\_index.de.md:18:4": failed to extract shortcode: template for shortcode "paige/image" not found


Code that references (example):
<p>{{% paige/image alt="Banner" breakpoints=true class="object-fit-cover rounded-4" fetchpriority="width" height="20rem" loading="eager" process="webp" src="img/banner_cropped.jpg" width="100%" %}} </p>


For my toml please see:
https://github.com/raumkauz/homepage/blob/main/hugo.toml

**Comment by willfaught** [comment]
What is the output when you build the example site?

**Comment by willfaught** [comment]
When I build your site, I don't get an error:

```
~/homepage main
❯ hugo server --enableGitInfo
hugo: downloading modules …
hugo: collected modules in 13714 ms
Watching for changes in /Users/will/homepage/{content,layouts,static}
Watching for config changes in /Users/will/homepage/hugo.toml, /Users/will/homepage/go.mod
Start building sites … 
hugo v0.123.7-312735366b20d64bd61bff8627f593749f86c964+extended darwin/arm64 BuildDate=2024-03-01T16:16:06Z VendorInfo=brew


                   | DE  | EN   
-------------------+-----+------
  Pages            |  27 |  25  
  Paginator pages  |   0 |   0  
  Non-page files   |   0 |   0  
  Static files     | 171 | 171  
  Processed images |   0 |   0  
  Aliases          |   2 |   1  
  Cleaned          |   0 |   0  

Built in 254 ms
Environment: "development"
Serving pages from disk
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1) 
Press Ctrl+C to stop
```

Your hugo.toml looks correct to me. I'm not sure what the issue is. Perhaps your tools are faulty in some way? Try uninstalling them and installing the latest versions.

**Comment by raumkauz** [comment]
okay, thanks for checking - I'll test that asap and report results.

**Comment by raumkauz** [comment]
Thanks for your patience and sorry for the late follow up on this - upgrading to newest hugo (v0.123.8 +extended) fixed the issue with the shortcodes, I didn't have to update the other tools, but I might consider updating those later on. 

Thank you for your assistance and have a nice day.

**Comment by willfaught** [comment]
Glad to hear it! :)
