### ISSUE TITLE
Feature Request: Change categories, tags from text to pills

### ISSUE THREAD

**Issue by saurabh-sm** [willfaught/paige#63]
Please bring this feature back :)

Categories and tags look really good in a list layout the way the were. When pages were listed in a menu section, there was clear distinction between the title, description, keywords (tags and categories), and author.

**Comment by willfaught** [comment]
I added a paige.keyword_style configuration in v0.78.0. You want to set it to "pills".

**Comment by saurabh-sm** [comment]
Thank you so much !!

Tested with v0.78.0
