### ISSUE TITLE
Table spacing is cramped

### ISSUE THREAD

**Issue by saurabh-sm** [willfaught/paige#66]
The spacing between tables is [not wide enough](https://willfaught.com/paige/content/markdown-syntax/#tables). 

They look pretty cramped in general. More spacing or having lines will make reading the table data easier.

**Comment by willfaught** [comment]
Bootstrap table styles aren't applied automatically. You have to set the "table" class yourself:

```html
<table class="table">
<tr>
<td>Italics</td>
<td>Bold</td>
<td>Code</td>
</tr>
<tr>
<td><i>italics</i></td>
<td><b>bold</b></td>
<td><code>code</code></td>
</tr>
</table>
```

See https://getbootstrap.com/docs/5.3/content/tables/#overview.

Note that if you want to use the Markdown table syntax, it's possible to specify the table class in Markdown too:

https://discourse.gohugo.io/t/render-hooks-for-tables/37550/3?u=will

I added a default padding of 0.5rem to td and th in v0.80.0.

**Comment by willfaught** [comment]
Changed the padding to 0.25rem in v0.80.1.

**Comment by saurabh-sm** [comment]
Thanks, 0.25rem looks better.
