### ISSUE TITLE
Request for custom web fonts support

### ISSUE THREAD

**Issue by B-Interactive** [willfaught/paige#7]
Hugo is still pretty new territory for me, so please let me know if I've approached this the wrong way.  That said, I have hunted for an official way, or best practice for making use of web fonts, but standard method seems to be entirely missing.

That is, it seems it's open to theme developers to implement this, should they choose to.

At the moment, in order to make updating the theme simpler, I've resorted to overriding only the [head.html](https://github.com/willfaught/paige/blob/master/layouts/partials/paige/head.html) partial.  I modify it to point to `paige/myLinks.html` and `paige/myStyle.html`, _instead of_ the original `paige/links.html` and `paige/style.html` partials respectively.
```
{{ partial "paige/myLinks.html" $page }}
{{ partial "paige/myStyle.html" $page }}
```

Having created those files, they then reference the original partials, so any theme updates to those are sustained, but it still permits me to include my custom additions:

**paige/myLinks.html**
```
{{ $page := . }}
{{ partial "paige/links.html" $page }}

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
```

**paige/myStyle.html**
```
{{ $page := . }}
{{ partial "paige/style.html" $page }}

<style>
    body, html {
        font-family: 'Roboto', sans-serif;
    }
</style>
```

Whilst this is working, theme updates to `/themes/paige/layouts/partials/paige/head.html` will be missed unless I manually review it each time.  I wonder you might consider a more elegant way to reference web fonts with theme support, within config.toml / .yaml, etc.

**Comment by willfaught** [comment]
Hi, @B-Interactive! Thanks for your question.

See https://github.com/willfaught/paige#include. You'll want to create a `partials/paige/head-last.html` file with your web font tags. `partials/paige/head.html` will include `head-last.html` at the end of the head tag if it exists. That way you don't have to override theme code, and you get all the updates automatically.

Please let me know if the include section in the readme was unclear about how it works, or why you'd want to use it. It's a work in progress.

**Comment by B-Interactive** [comment]
Ah!  That's exactly what I needed, that's great!

I come from WordPress, so I'm looking for ways to hook in code, and there it is, laid out beautifully, thank you.
