### ISSUE TITLE
Previous and next page have opposite arrows

### ISSUE THREAD

**Issue by saurabh-sm** [willfaught/paige#75]
On [this webpage](https://willfaught.com/paige/customization/style/), there are two pages - "Style Data" and "Show Data". These pages have weights 10 and 20 respectively. When navigating to the "Style Data" page and scrolling to the bottom, `← Show Data` is displayed instead of `→ Show Data`. 

The arrow `←` indicates previous and `→` indicates next. Since the page "Show Data" has a higher weight and is also listed after "Style Data", `→ Show Data` should be displayed to correctly reflect this.

**Comment by willfaught** [comment]
Thanks for the report. Can you confirm it's fixed in v0.85.0?

**Comment by saurabh-sm** [comment]
Yes it does ! Thank you !
