### ISSUE TITLE
Feature Request: Add Codeberg Icons

### ISSUE THREAD

**Issue by saurabh-sm** [willfaught/paige#77]
[Codeberg](https://codeberg.org) is a privacy respecting GitHub alternative.

The homepage of this theme uses Github's icon at the bottom. It would be nice to have the option of using the [Codeberg logo](https://codeberg.org/Codeberg/Design).

**Comment by willfaught** [comment]
It seems like you mean add a font icon for the Codeberg logo. It looks like [Bootstrap Icons](https://icons.getbootstrap.com) doesn't have one yet. I suggest waiting for Bootstrap Icons to add the Codeberg logo, or adding another icon font to your site that has the Codeberg logo, or using [the logo image](https://codeberg.org/Codeberg/Design/src/branch/main/logo/icon/png/codeberg-logo_icon_blue-64x64.png) directly with an img tag.

**Comment by saurabh-sm** [comment]
> or using [the logo image](https://codeberg.org/Codeberg/Design/src/branch/main/logo/icon/png/codeberg-logo_icon_blue-64x64.png) directly with an img tag.

I currently have:

```
<div class="column-gap-3 d-flex display-6 justify-content-center mb-3">
    {{< paige/icon class="bi bi-git" title="Codeberg" url="https://codeberg.org/myuser/myrepo" >}}
</div>
```

at the bottom of `_index.md`.

How do I used the img tag ?

**Comment by willfaught** [comment]
Something like:

```html
<img src="https://codeberg.org/Codeberg/Design/raw/branch/main/logo/icon/png/codeberg-logo_icon_blue-64x64.png">
```

Example:

<img src="https://codeberg.org/Codeberg/Design/raw/branch/main/logo/icon/png/codeberg-logo_icon_blue-64x64.png">

You will probably have to set the height explicitly to whatever the pixel count is for the height of the display-6 Bootstrap class, which seems to be 2.5rem:

```html
<div class="column-gap-3 d-flex display-6 justify-content-center mb-3">
    <img src="https://codeberg.org/Codeberg/Design/raw/branch/main/logo/icon/png/codeberg-logo_icon_blue-64x64.png" style="height:2.5rem">
</div>
```

**Comment by saurabh-sm** [comment]
Thank you !
