### ISSUE TITLE
Feature Request: Tab support for code blocks

### ISSUE THREAD

**Issue by saurabh-sm** [willfaught/paige#78]
There are a few pages in my site where I have code in 2 programming languages. These code blocks are language-specific implementations of Wikipedia's procedures ([sample link](https://en.wikipedia.org/wiki/Tree_traversal#Implementations)). They are around half page in length. 

Having multiple tabs would improve readability and provide better organization.

[Example "Hello, World!"](https://imfing.github.io/hextra/docs/guide/shortcodes/tabs/#use-markdown) in JSON, YAML, and TOML

Not sure how well this feature would fit into Paige's design aesthetics.

**Comment by willfaught** [comment]
Tabs are complicated to do in Bootstrap by hand, especially with multiple tab groups that have the same tab names, so I added tab shortcodes in v0.87.0. Please try them out.

**Comment by saurabh-sm** [comment]
Perfect !!
This is exactly what I was looking for, thanks a lot !
