### ISSUE TITLE
Feature Request: Footer enhancements (credit and license) through the configuration file

### ISSUE THREAD

**Issue by saurabh-sm** [willfaught/paige#79]
There's a way to specify copyright text in the configuration file like:

```
copyright = "© Firstname Lastname"
```

Requesting a feature to make the `credit` configurable. Currently if it is specified in the front matter, "Paige Theme" is displayed at the bottom. I'm looking to add text like "Powered by Paige theme" or "Powered by Hugo's Paige theme".

Also requesting a feature to make the license text visible in a similar manner.
For example "Code snippets are MIT licensed" at the bottom of [this page](https://www.alexedwards.net/blog/which-go-router-should-i-use)

**Comment by willfaught** [comment]
What do you mean by configurable credit? Do you mean a new line in the footer with customizable content, or overriding the "Paige Theme" content?

**Comment by saurabh-sm** [comment]
I mean overriding the "Paige Theme" content with something like "Powered by Paige theme" or "Powered by Hugo's Paige theme".

**Comment by willfaught** [comment]
This one lead down a couple rabbit holes. See the paige.credit and paige.license config in v0.89.0.

**Comment by saurabh-sm** [comment]
The number of changes made in 0.89 is massive.

[This](https://github.com/willfaught/paige/commit/ada7e4c8c17a6863fa21ad925cd86869767be3da) is also a great addition. 

Paige credit and license are working as expected.
