### ISSUE TITLE
Feature Request: Paige shortcode to fetch remote code

### ISSUE THREAD

**Issue by saurabh-sm** [willfaught/paige#80]
Having long code blocks in a markdown file can get verbose as two different things would need to be maintained - the actual notes / documentation and the code. If the code block has implementation and tests, continuous integration can't be run for it to perform validation and correctness.

Requesting a a Paige shortcode which fetches code from a file in a (public?) repository.

Related: https://github.com/willfaught/paige/issues/78

**Comment by willfaught** [comment]
See the paige/request shortcode in v0.90.0.

**Comment by saurabh-sm** [comment]
Looks like it doesn't highlight code. 

For instance if you add the below to a `.md` file, the code gets is retrieved but not highlighted:

```
<pre>
{{< paige/request "https://codeberg.org/saurabh/zigling/raw/branch/main/src/card_tricks.zig" >}}
</pre>

```

**Comment by willfaught** [comment]
You would need to wrap paige/request in a paige/code instead of a pre.

**Comment by saurabh-sm** [comment]
Gotcha!

I've updated the markdown content to:

```
{{< paige/code lang="zig" >}}
	{{< paige/request "https://codeberg.org/saurabh/zigling/raw/branch/main/src/card_tricks.zig" >}}
{{< /paige/code >}}
```

and have noticed some issue with text parsing:

+ `const std = @import(&#34;std&#34;)` (line 1)

+ `if` conditions (lines 14 and 27)

+ quotation marks in all test statements

+ `&amp` in `try cards.appendSlice` (all test functions)

+ `const expected` in the last three test cases

**Comment by saurabh-sm** [comment]
The code block also has some space before all lines, i.e., it is not left indented like other content

**Comment by willfaught** [comment]
Correct. Unfortunately, indentation doesn't mix well with shortcodes. I always avoid indentation with them.

Your escaping issue remains. The paige/request shortcode output is HTML-escaped, then inside the paige/code shortcode, the built-in highlight shortcode HTML-escapes the output again. I don't see a way to prevent the paige/request shortcode result text from being HTML-escaped in the first place. I could HTML-unescape all paige/code shortcode input to avoid this particular issue, but then that would mysteriously convert paige/code shortcode input like `<!-- Use HTML entities like &amp; -->` to `<!-- Use HTML entities like & -->`.

In v0.90.1, the paige/code shortcode has a new "unescape" parameter that, when true, HTML-unescapes the inner/body value of the shortcode. The content is then re-HTML-escaped when passed to the highlight shortcode.

**Comment by saurabh-sm** [comment]
Thanks a lot!! 

Things are rendering correctly with:

```
{{< paige/code
    lang="zig"
    unescape=true >}}
{{< paige/request "https://codeberg.org/saurabh/zigling/raw/branch/main/src/card_tricks.zig" >}}
{{< /paige/code >}}
```
