### ISSUE TITLE
Alert is not shown when title and reading_time are disabled

### ISSUE THREAD

**Issue by scluff** [willfaught/paige#82]
hugo.toml
```
[params.paige.page]
disable_title = true
disable_reading_time = true
```
For a specific page, have an alert defined in the front matter
```
[paige.alert]
message = "Some alert message."
type = "danger"
```
Believe this is because the following line is missing `$alert`
https://github.com/willfaught/paige/blob/30d7650bda518bb4334b46b7b22333a5c354fa83/layouts/partials/paige/page-header.html#L21

**Comment by willfaught** [comment]
Thanks for the report. It should be fixed in v0.90.2.
